version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3883 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3883:3883"
    depends_on:
      - db
